/*
 * This Java source file was generated by the Gradle 'init' task.
 */
package toDoApp;

import controls.ProjectsControls;
import controls.TaskControls;
import java.sql.SQLException;
import java.text.SimpleDateFormat;
import java.util.Date;
import java.util.List;
import java.util.logging.Level;
import java.util.logging.Logger;
import models.Projects;
import models.Tasks;

public class App {

    public static void main(String[] args) throws SQLException {
        ProjectsControls controller = new ProjectsControls();

        TaskControls tasks = new TaskControls();
        SimpleDateFormat formatter = new SimpleDateFormat("dd/MM/yyyy");

        Tasks task = new Tasks();
        
        task.setName("Olá mundo 2");
        task.setDescription("testando mais uma vez o update");
        task.setId_project(6);
        task.setCompleted(new Date(2032-12-12));
        
        tasks.removeById(20);
        
        
        
        

        

    }
}
